spring:
  application:
    name: RestAPI              # ?????? ?? (??, ????, ??? ?? ?? ???)
  profiles:
    active: dev                # ?? ???? profile (?: dev, prod, test)
  output:
    ansi:
      enabled: always          # ?? ?? ? ANSI ?? ?? ?? (?? ?? ??)
  datasource:
    hikari:
      auto-commit: false       # HikariCP ??? ??? ?? ???? ???? (???? ?? ??)
  jackson:
    serialization:
      fail-on-empty-beans: false  # ? ?? ??? ?? ??
  jpa:
    show-sql: true             # JPA ?? SQL ??? ??
    hibernate:
      ddl-auto: update         # ??? ?? ?? ?? (update: ??? ?? ? ??? ?? ????)
    properties:
      hibernate:
        format_sql: true       # SQL? ?? ?? ????? ??
        highlight_sql: true    # SQL ?? ?? ??
        use_sql_comments: true # SQL? JPA? ?? ??? ??? ?? ??
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE        # ???? SQL ???? ?? ?? (TRACE ??, ?? ??)
    org.hibernate.orm.jdbc.extract: TRACE     # JDBC ?? ?? ?? ?? ??
    org.springframework.transaction.interceptor: TRACE # ???? ??/??/?? ?? ?? ??
